version: "3.9"
services:
  mysql: 
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret  
      - MYSQL_DATABASE=gochat
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"  # Exposed port for MySQL

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=mysql://root:secret@mysql:3306/gochat?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql 
    command: [ "/app/main" ]
